# Generated by Django 2.1.3 on 2018-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estuadiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('edad', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
